s="raju"
print(s)
print(len(s))
print(s.upper())
print(s.lower())
print(s.title())
print(s.swapcase())
print(s.casefold())
print(s.center(10,"*"))
print(s.ljust(5,"-"))
print(s.zfill(8))
print(s.find("5"))
print(s.rfind("3"))
print(s.count("r"))
print(s.startswith("r"))
print(s.endswith("j"))
print(s.split("," ))
print(s.rsplit(","))
print(s.rsplit(","  '1'))
print(s)
d="rani raju"
print(d)
print(d)
print(d.join(["raju", "rani"]))